// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdQQrKSngz2SSa8E4x1WS7zUY_U5XfXrU',
    appId: '1:607896212329:web:14e0f16fecea1e45dae3f8',
    messagingSenderId: '607896212329',
    projectId: 'expensify-fdd9b',
    authDomain: 'expensify-fdd9b.firebaseapp.com',
    storageBucket: 'expensify-fdd9b.appspot.com',
    measurementId: 'G-5K2GNTV6RM',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdQQrKSngz2SSa8E4x1WS7zUY_U5XfXrU',
    appId: '1:607896212329:web:a415f1a8a592f2ecdae3f8',
    messagingSenderId: '607896212329',
    projectId: 'expensify-fdd9b',
    authDomain: 'expensify-fdd9b.firebaseapp.com',
    storageBucket: 'expensify-fdd9b.appspot.com',
    measurementId: 'G-5SLY159RSN',
  );
}
